FROM node:12.18.1
ENV NODE_ENV=production

WORKDIR /opt/app

COPY ["api/package.json", "api/package-lock.json*", "./"]
RUN npm install --production
RUN npm install react-scripts@3.4.1 -g --silent

COPY . .

CMD ["npm", "start"]
